package com.smartcommunity.pojo;

import java.util.Date;

public class AccountRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.id
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.meterid
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private Integer meterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.roomnumber
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.date
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.shouldpay
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private Float shouldpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.actualpay
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private Float actualpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.type
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_record.param
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    private String param;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.id
     *
     * @return the value of account_record.id
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.id
     *
     * @param id the value for account_record.id
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.meterid
     *
     * @return the value of account_record.meterid
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public Integer getMeterid() {
        return meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.meterid
     *
     * @param meterid the value for account_record.meterid
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setMeterid(Integer meterid) {
        this.meterid = meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.roomnumber
     *
     * @return the value of account_record.roomnumber
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.roomnumber
     *
     * @param roomnumber the value for account_record.roomnumber
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.date
     *
     * @return the value of account_record.date
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.date
     *
     * @param date the value for account_record.date
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.shouldpay
     *
     * @return the value of account_record.shouldpay
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public Float getShouldpay() {
        return shouldpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.shouldpay
     *
     * @param shouldpay the value for account_record.shouldpay
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setShouldpay(Float shouldpay) {
        this.shouldpay = shouldpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.actualpay
     *
     * @return the value of account_record.actualpay
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public Float getActualpay() {
        return actualpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.actualpay
     *
     * @param actualpay the value for account_record.actualpay
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setActualpay(Float actualpay) {
        this.actualpay = actualpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.type
     *
     * @return the value of account_record.type
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.type
     *
     * @param type the value for account_record.type
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_record.param
     *
     * @return the value of account_record.param
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_record.param
     *
     * @param param the value for account_record.param
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }
}