package com.smartcommunity.pojo;

public class Complaintsimages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaintsimages.id
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaintsimages.complaintsid
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    private Integer complaintsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaintsimages.url
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaintsimages.id
     *
     * @return the value of complaintsimages.id
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaintsimages.id
     *
     * @param id the value for complaintsimages.id
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaintsimages.complaintsid
     *
     * @return the value of complaintsimages.complaintsid
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    public Integer getComplaintsid() {
        return complaintsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaintsimages.complaintsid
     *
     * @param complaintsid the value for complaintsimages.complaintsid
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    public void setComplaintsid(Integer complaintsid) {
        this.complaintsid = complaintsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaintsimages.url
     *
     * @return the value of complaintsimages.url
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaintsimages.url
     *
     * @param url the value for complaintsimages.url
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}