package com.smartcommunity.pojo;

import java.util.Date;

public class Complaints {
	/**
	 * add
	 */
	private java.util.List<Complaintsimages> complaintsimages;

	public java.util.List<Complaintsimages> getComplaintsimages() {
		return complaintsimages;
	}

	public void setComplaintsimages(java.util.List<Complaintsimages> complaintsimages) {
		this.complaintsimages = complaintsimages;
	}
	/**
	 * addend
	 */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.id
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.roomnumber
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.name
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.phone
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.time
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.content
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.requiredresult
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private String requiredresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.processedsituation
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private String processedsituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.remarks
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.processedstate
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private Integer processedstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaints.processedtime
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    private Date processedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.id
     *
     * @return the value of complaints.id
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.id
     *
     * @param id the value for complaints.id
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.roomnumber
     *
     * @return the value of complaints.roomnumber
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.roomnumber
     *
     * @param roomnumber the value for complaints.roomnumber
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.name
     *
     * @return the value of complaints.name
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.name
     *
     * @param name the value for complaints.name
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.phone
     *
     * @return the value of complaints.phone
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.phone
     *
     * @param phone the value for complaints.phone
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.time
     *
     * @return the value of complaints.time
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.time
     *
     * @param time the value for complaints.time
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.content
     *
     * @return the value of complaints.content
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.content
     *
     * @param content the value for complaints.content
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.requiredresult
     *
     * @return the value of complaints.requiredresult
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public String getRequiredresult() {
        return requiredresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.requiredresult
     *
     * @param requiredresult the value for complaints.requiredresult
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setRequiredresult(String requiredresult) {
        this.requiredresult = requiredresult == null ? null : requiredresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.processedsituation
     *
     * @return the value of complaints.processedsituation
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public String getProcessedsituation() {
        return processedsituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.processedsituation
     *
     * @param processedsituation the value for complaints.processedsituation
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setProcessedsituation(String processedsituation) {
        this.processedsituation = processedsituation == null ? null : processedsituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.remarks
     *
     * @return the value of complaints.remarks
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.remarks
     *
     * @param remarks the value for complaints.remarks
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.processedstate
     *
     * @return the value of complaints.processedstate
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public Integer getProcessedstate() {
        return processedstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.processedstate
     *
     * @param processedstate the value for complaints.processedstate
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setProcessedstate(Integer processedstate) {
        this.processedstate = processedstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaints.processedtime
     *
     * @return the value of complaints.processedtime
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public Date getProcessedtime() {
        return processedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaints.processedtime
     *
     * @param processedtime the value for complaints.processedtime
     *
     * @mbggenerated Fri Jan 16 09:42:45 CST 2015
     */
    public void setProcessedtime(Date processedtime) {
        this.processedtime = processedtime;
    }
}