package com.smartcommunity.pojo;

import java.util.Date;

public class Decoratefee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.id
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.roomnumber
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.ownername
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private String ownername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.date
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.deposit
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Float deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.rabishfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Float rabishfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.elecfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Float elecfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.waterfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Float waterfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.passfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Float passfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoratefee.remarks
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.id
     *
     * @return the value of decoratefee.id
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.id
     *
     * @param id the value for decoratefee.id
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.roomnumber
     *
     * @return the value of decoratefee.roomnumber
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.roomnumber
     *
     * @param roomnumber the value for decoratefee.roomnumber
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.ownername
     *
     * @return the value of decoratefee.ownername
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.ownername
     *
     * @param ownername the value for decoratefee.ownername
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername == null ? null : ownername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.date
     *
     * @return the value of decoratefee.date
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.date
     *
     * @param date the value for decoratefee.date
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.deposit
     *
     * @return the value of decoratefee.deposit
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Float getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.deposit
     *
     * @param deposit the value for decoratefee.deposit
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setDeposit(Float deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.rabishfee
     *
     * @return the value of decoratefee.rabishfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Float getRabishfee() {
        return rabishfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.rabishfee
     *
     * @param rabishfee the value for decoratefee.rabishfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setRabishfee(Float rabishfee) {
        this.rabishfee = rabishfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.elecfee
     *
     * @return the value of decoratefee.elecfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Float getElecfee() {
        return elecfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.elecfee
     *
     * @param elecfee the value for decoratefee.elecfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setElecfee(Float elecfee) {
        this.elecfee = elecfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.waterfee
     *
     * @return the value of decoratefee.waterfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Float getWaterfee() {
        return waterfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.waterfee
     *
     * @param waterfee the value for decoratefee.waterfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setWaterfee(Float waterfee) {
        this.waterfee = waterfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.passfee
     *
     * @return the value of decoratefee.passfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Float getPassfee() {
        return passfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.passfee
     *
     * @param passfee the value for decoratefee.passfee
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setPassfee(Float passfee) {
        this.passfee = passfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoratefee.remarks
     *
     * @return the value of decoratefee.remarks
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoratefee.remarks
     *
     * @param remarks the value for decoratefee.remarks
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}