package com.smartcommunity.pojo;

public class Decorate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.id
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.roomnumber
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.ownername
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private String ownername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.phone
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.isjianzhuang
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Boolean isjianzhuang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.hasdecprotocol
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Boolean hasdecprotocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.hasdecform
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Boolean hasdecform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.hasdeclicence
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Boolean hasdeclicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.remarks
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decorate.iscomplete
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    private Boolean iscomplete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.id
     *
     * @return the value of decorate.id
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.id
     *
     * @param id the value for decorate.id
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.roomnumber
     *
     * @return the value of decorate.roomnumber
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.roomnumber
     *
     * @param roomnumber the value for decorate.roomnumber
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.ownername
     *
     * @return the value of decorate.ownername
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.ownername
     *
     * @param ownername the value for decorate.ownername
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername == null ? null : ownername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.phone
     *
     * @return the value of decorate.phone
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.phone
     *
     * @param phone the value for decorate.phone
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.isjianzhuang
     *
     * @return the value of decorate.isjianzhuang
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Boolean getIsjianzhuang() {
        return isjianzhuang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.isjianzhuang
     *
     * @param isjianzhuang the value for decorate.isjianzhuang
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setIsjianzhuang(Boolean isjianzhuang) {
        this.isjianzhuang = isjianzhuang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.hasdecprotocol
     *
     * @return the value of decorate.hasdecprotocol
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Boolean getHasdecprotocol() {
        return hasdecprotocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.hasdecprotocol
     *
     * @param hasdecprotocol the value for decorate.hasdecprotocol
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setHasdecprotocol(Boolean hasdecprotocol) {
        this.hasdecprotocol = hasdecprotocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.hasdecform
     *
     * @return the value of decorate.hasdecform
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Boolean getHasdecform() {
        return hasdecform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.hasdecform
     *
     * @param hasdecform the value for decorate.hasdecform
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setHasdecform(Boolean hasdecform) {
        this.hasdecform = hasdecform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.hasdeclicence
     *
     * @return the value of decorate.hasdeclicence
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Boolean getHasdeclicence() {
        return hasdeclicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.hasdeclicence
     *
     * @param hasdeclicence the value for decorate.hasdeclicence
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setHasdeclicence(Boolean hasdeclicence) {
        this.hasdeclicence = hasdeclicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.remarks
     *
     * @return the value of decorate.remarks
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.remarks
     *
     * @param remarks the value for decorate.remarks
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decorate.iscomplete
     *
     * @return the value of decorate.iscomplete
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public Boolean getIscomplete() {
        return iscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decorate.iscomplete
     *
     * @param iscomplete the value for decorate.iscomplete
     *
     * @mbggenerated Tue Jan 20 13:50:49 CST 2015
     */
    public void setIscomplete(Boolean iscomplete) {
        this.iscomplete = iscomplete;
    }
}