package com.smartcommunity.pojo;

public class Devicefault {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicefault.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicefault.deviceid
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private Integer deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicefault.devicestate
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private String devicestate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicefault.id
     *
     * @return the value of devicefault.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicefault.id
     *
     * @param id the value for devicefault.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicefault.deviceid
     *
     * @return the value of devicefault.deviceid
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicefault.deviceid
     *
     * @param deviceid the value for devicefault.deviceid
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicefault.devicestate
     *
     * @return the value of devicefault.devicestate
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public String getDevicestate() {
        return devicestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicefault.devicestate
     *
     * @param devicestate the value for devicefault.devicestate
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setDevicestate(String devicestate) {
        this.devicestate = devicestate == null ? null : devicestate.trim();
    }
}