package com.smartcommunity.pojo;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.devicename
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private String devicename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.devicename
     *
     * @return the value of device.devicename
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public String getDevicename() {
        return devicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.devicename
     *
     * @param devicename the value for device.devicename
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setDevicename(String devicename) {
        this.devicename = devicename == null ? null : devicename.trim();
    }
}