package com.smartcommunity.pojo;

import java.util.Date;

public class Meter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.id
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.roomnumber
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.metertype
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Integer metertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.meternumber
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private String meternumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.readman
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private String readman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.readdata
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Float readdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.consumedata
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Float consumedata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.readingtime
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Date readingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.uniteprice
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Float uniteprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.totalprice
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Float totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.version
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter.state
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.id
     *
     * @return the value of meter.id
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.id
     *
     * @param id the value for meter.id
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.roomnumber
     *
     * @return the value of meter.roomnumber
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.roomnumber
     *
     * @param roomnumber the value for meter.roomnumber
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.metertype
     *
     * @return the value of meter.metertype
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Integer getMetertype() {
        return metertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.metertype
     *
     * @param metertype the value for meter.metertype
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setMetertype(Integer metertype) {
        this.metertype = metertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.meternumber
     *
     * @return the value of meter.meternumber
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public String getMeternumber() {
        return meternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.meternumber
     *
     * @param meternumber the value for meter.meternumber
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setMeternumber(String meternumber) {
        this.meternumber = meternumber == null ? null : meternumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.readman
     *
     * @return the value of meter.readman
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public String getReadman() {
        return readman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.readman
     *
     * @param readman the value for meter.readman
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setReadman(String readman) {
        this.readman = readman == null ? null : readman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.readdata
     *
     * @return the value of meter.readdata
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Float getReaddata() {
        return readdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.readdata
     *
     * @param readdata the value for meter.readdata
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setReaddata(Float readdata) {
        this.readdata = readdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.consumedata
     *
     * @return the value of meter.consumedata
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Float getConsumedata() {
        return consumedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.consumedata
     *
     * @param consumedata the value for meter.consumedata
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setConsumedata(Float consumedata) {
        this.consumedata = consumedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.readingtime
     *
     * @return the value of meter.readingtime
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Date getReadingtime() {
        return readingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.readingtime
     *
     * @param readingtime the value for meter.readingtime
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setReadingtime(Date readingtime) {
        this.readingtime = readingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.uniteprice
     *
     * @return the value of meter.uniteprice
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Float getUniteprice() {
        return uniteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.uniteprice
     *
     * @param uniteprice the value for meter.uniteprice
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setUniteprice(Float uniteprice) {
        this.uniteprice = uniteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.totalprice
     *
     * @return the value of meter.totalprice
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Float getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.totalprice
     *
     * @param totalprice the value for meter.totalprice
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setTotalprice(Float totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.version
     *
     * @return the value of meter.version
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.version
     *
     * @param version the value for meter.version
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meter.state
     *
     * @return the value of meter.state
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meter.state
     *
     * @param state the value for meter.state
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    public void setState(Boolean state) {
        this.state = state;
    }
}