package com.smartcommunity.pojo;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.date
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.author
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.room
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    private String room;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.date
     *
     * @return the value of notice.date
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.date
     *
     * @param date the value for notice.date
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.author
     *
     * @return the value of notice.author
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.author
     *
     * @param author the value for notice.author
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.room
     *
     * @return the value of notice.room
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.room
     *
     * @param room the value for notice.room
     *
     * @mbggenerated Sun Jan 25 17:22:54 CST 2015
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }
}