package com.smartcommunity.pojo;

import java.util.Date;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.buildingnumber
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Integer buildingnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.number
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.user
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Integer user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.buildingarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Float buildingarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.innerarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Float innerarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.publicarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Float publicarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.state
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.type
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.floor
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.targetgroup
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private String targetgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.startcharge
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    private Date startcharge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.buildingnumber
     *
     * @return the value of room.buildingnumber
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Integer getBuildingnumber() {
        return buildingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.buildingnumber
     *
     * @param buildingnumber the value for room.buildingnumber
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setBuildingnumber(Integer buildingnumber) {
        this.buildingnumber = buildingnumber ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.number
     *
     * @return the value of room.number
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.number
     *
     * @param number the value for room.number
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.user
     *
     * @return the value of room.user
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.user
     *
     * @param user the value for room.user
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.buildingarea
     *
     * @return the value of room.buildingarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Float getBuildingarea() {
        return buildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.buildingarea
     *
     * @param buildingarea the value for room.buildingarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setBuildingarea(Float buildingarea) {
        this.buildingarea = buildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.innerarea
     *
     * @return the value of room.innerarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Float getInnerarea() {
        return innerarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.innerarea
     *
     * @param innerarea the value for room.innerarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setInnerarea(Float innerarea) {
        this.innerarea = innerarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.publicarea
     *
     * @return the value of room.publicarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Float getPublicarea() {
        return publicarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.publicarea
     *
     * @param publicarea the value for room.publicarea
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setPublicarea(Float publicarea) {
        this.publicarea = publicarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.state
     *
     * @return the value of room.state
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.state
     *
     * @param state the value for room.state
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.type
     *
     * @return the value of room.type
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.type
     *
     * @param type the value for room.type
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.floor
     *
     * @return the value of room.floor
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.floor
     *
     * @param floor the value for room.floor
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.targetgroup
     *
     * @return the value of room.targetgroup
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public String getTargetgroup() {
        return targetgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.targetgroup
     *
     * @param targetgroup the value for room.targetgroup
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setTargetgroup(String targetgroup) {
        this.targetgroup = targetgroup == null ? null : targetgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.startcharge
     *
     * @return the value of room.startcharge
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public Date getStartcharge() {
        return startcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.startcharge
     *
     * @param startcharge the value for room.startcharge
     *
     * @mbggenerated Tue Jan 13 16:05:47 CST 2015
     */
    public void setStartcharge(Date startcharge) {
        this.startcharge = startcharge;
    }
}