package com.smartcommunity.pojo;

import java.util.Date;

public class Roomowner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.id
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.tenantnumber
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String tenantnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.roomnumber
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.type
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.name
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.sex
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.identity
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.nativeplace
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String nativeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.registeredresidence
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String registeredresidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.nation
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.politicalaffiliation
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String politicalaffiliation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.educationlevel
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String educationlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.company
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.maritalstatus
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String maritalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.hobbies
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String hobbies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.telephone
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.qq
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.mail
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.immigratedate
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private Date immigratedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.quitdate
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private Date quitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.propertyowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String propertyowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.propertyowneridentity
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private String propertyowneridentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomowner.userpassid
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    private Integer userpassid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.id
     *
     * @return the value of roomowner.id
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.id
     *
     * @param id the value for roomowner.id
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.tenantnumber
     *
     * @return the value of roomowner.tenantnumber
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getTenantnumber() {
        return tenantnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.tenantnumber
     *
     * @param tenantnumber the value for roomowner.tenantnumber
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setTenantnumber(String tenantnumber) {
        this.tenantnumber = tenantnumber == null ? null : tenantnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.roomnumber
     *
     * @return the value of roomowner.roomnumber
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.roomnumber
     *
     * @param roomnumber the value for roomowner.roomnumber
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.type
     *
     * @return the value of roomowner.type
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.type
     *
     * @param type the value for roomowner.type
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.name
     *
     * @return the value of roomowner.name
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.name
     *
     * @param name the value for roomowner.name
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.sex
     *
     * @return the value of roomowner.sex
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.sex
     *
     * @param sex the value for roomowner.sex
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.identity
     *
     * @return the value of roomowner.identity
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.identity
     *
     * @param identity the value for roomowner.identity
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.nativeplace
     *
     * @return the value of roomowner.nativeplace
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.nativeplace
     *
     * @param nativeplace the value for roomowner.nativeplace
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace == null ? null : nativeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.registeredresidence
     *
     * @return the value of roomowner.registeredresidence
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getRegisteredresidence() {
        return registeredresidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.registeredresidence
     *
     * @param registeredresidence the value for roomowner.registeredresidence
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setRegisteredresidence(String registeredresidence) {
        this.registeredresidence = registeredresidence == null ? null : registeredresidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.nation
     *
     * @return the value of roomowner.nation
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.nation
     *
     * @param nation the value for roomowner.nation
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.politicalaffiliation
     *
     * @return the value of roomowner.politicalaffiliation
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getPoliticalaffiliation() {
        return politicalaffiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.politicalaffiliation
     *
     * @param politicalaffiliation the value for roomowner.politicalaffiliation
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setPoliticalaffiliation(String politicalaffiliation) {
        this.politicalaffiliation = politicalaffiliation == null ? null : politicalaffiliation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.educationlevel
     *
     * @return the value of roomowner.educationlevel
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getEducationlevel() {
        return educationlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.educationlevel
     *
     * @param educationlevel the value for roomowner.educationlevel
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setEducationlevel(String educationlevel) {
        this.educationlevel = educationlevel == null ? null : educationlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.company
     *
     * @return the value of roomowner.company
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.company
     *
     * @param company the value for roomowner.company
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.maritalstatus
     *
     * @return the value of roomowner.maritalstatus
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getMaritalstatus() {
        return maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.maritalstatus
     *
     * @param maritalstatus the value for roomowner.maritalstatus
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus == null ? null : maritalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.hobbies
     *
     * @return the value of roomowner.hobbies
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getHobbies() {
        return hobbies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.hobbies
     *
     * @param hobbies the value for roomowner.hobbies
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setHobbies(String hobbies) {
        this.hobbies = hobbies == null ? null : hobbies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.telephone
     *
     * @return the value of roomowner.telephone
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.telephone
     *
     * @param telephone the value for roomowner.telephone
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.qq
     *
     * @return the value of roomowner.qq
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.qq
     *
     * @param qq the value for roomowner.qq
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.mail
     *
     * @return the value of roomowner.mail
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.mail
     *
     * @param mail the value for roomowner.mail
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.immigratedate
     *
     * @return the value of roomowner.immigratedate
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public Date getImmigratedate() {
        return immigratedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.immigratedate
     *
     * @param immigratedate the value for roomowner.immigratedate
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setImmigratedate(Date immigratedate) {
        this.immigratedate = immigratedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.quitdate
     *
     * @return the value of roomowner.quitdate
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public Date getQuitdate() {
        return quitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.quitdate
     *
     * @param quitdate the value for roomowner.quitdate
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setQuitdate(Date quitdate) {
        this.quitdate = quitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.propertyowner
     *
     * @return the value of roomowner.propertyowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getPropertyowner() {
        return propertyowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.propertyowner
     *
     * @param propertyowner the value for roomowner.propertyowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setPropertyowner(String propertyowner) {
        this.propertyowner = propertyowner == null ? null : propertyowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.propertyowneridentity
     *
     * @return the value of roomowner.propertyowneridentity
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getPropertyowneridentity() {
        return propertyowneridentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.propertyowneridentity
     *
     * @param propertyowneridentity the value for roomowner.propertyowneridentity
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setPropertyowneridentity(String propertyowneridentity) {
        this.propertyowneridentity = propertyowneridentity == null ? null : propertyowneridentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomowner.userpassid
     *
     * @return the value of roomowner.userpassid
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public Integer getUserpassid() {
        return userpassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomowner.userpassid
     *
     * @param userpassid the value for roomowner.userpassid
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setUserpassid(Integer userpassid) {
        this.userpassid = userpassid;
    }
}