package com.smartcommunity.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RoomownerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public RoomownerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTenantnumberIsNull() {
            addCriterion("tenantnumber is null");
            return (Criteria) this;
        }

        public Criteria andTenantnumberIsNotNull() {
            addCriterion("tenantnumber is not null");
            return (Criteria) this;
        }

        public Criteria andTenantnumberEqualTo(String value) {
            addCriterion("tenantnumber =", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberNotEqualTo(String value) {
            addCriterion("tenantnumber <>", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberGreaterThan(String value) {
            addCriterion("tenantnumber >", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberGreaterThanOrEqualTo(String value) {
            addCriterion("tenantnumber >=", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberLessThan(String value) {
            addCriterion("tenantnumber <", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberLessThanOrEqualTo(String value) {
            addCriterion("tenantnumber <=", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberLike(String value) {
            addCriterion("tenantnumber like", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberNotLike(String value) {
            addCriterion("tenantnumber not like", value, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberIn(List<String> values) {
            addCriterion("tenantnumber in", values, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberNotIn(List<String> values) {
            addCriterion("tenantnumber not in", values, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberBetween(String value1, String value2) {
            addCriterion("tenantnumber between", value1, value2, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andTenantnumberNotBetween(String value1, String value2) {
            addCriterion("tenantnumber not between", value1, value2, "tenantnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberIsNull() {
            addCriterion("roomnumber is null");
            return (Criteria) this;
        }

        public Criteria andRoomnumberIsNotNull() {
            addCriterion("roomnumber is not null");
            return (Criteria) this;
        }

        public Criteria andRoomnumberEqualTo(String value) {
            addCriterion("roomnumber =", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotEqualTo(String value) {
            addCriterion("roomnumber <>", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberGreaterThan(String value) {
            addCriterion("roomnumber >", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberGreaterThanOrEqualTo(String value) {
            addCriterion("roomnumber >=", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberLessThan(String value) {
            addCriterion("roomnumber <", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberLessThanOrEqualTo(String value) {
            addCriterion("roomnumber <=", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberLike(String value) {
            addCriterion("roomnumber like", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotLike(String value) {
            addCriterion("roomnumber not like", value, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberIn(List<String> values) {
            addCriterion("roomnumber in", values, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotIn(List<String> values) {
            addCriterion("roomnumber not in", values, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberBetween(String value1, String value2) {
            addCriterion("roomnumber between", value1, value2, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andRoomnumberNotBetween(String value1, String value2) {
            addCriterion("roomnumber not between", value1, value2, "roomnumber");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andIdentityIsNull() {
            addCriterion("identity is null");
            return (Criteria) this;
        }

        public Criteria andIdentityIsNotNull() {
            addCriterion("identity is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityEqualTo(String value) {
            addCriterion("identity =", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotEqualTo(String value) {
            addCriterion("identity <>", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityGreaterThan(String value) {
            addCriterion("identity >", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("identity >=", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLessThan(String value) {
            addCriterion("identity <", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLessThanOrEqualTo(String value) {
            addCriterion("identity <=", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLike(String value) {
            addCriterion("identity like", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotLike(String value) {
            addCriterion("identity not like", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityIn(List<String> values) {
            addCriterion("identity in", values, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotIn(List<String> values) {
            addCriterion("identity not in", values, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityBetween(String value1, String value2) {
            addCriterion("identity between", value1, value2, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotBetween(String value1, String value2) {
            addCriterion("identity not between", value1, value2, "identity");
            return (Criteria) this;
        }

        public Criteria andNativeplaceIsNull() {
            addCriterion("nativeplace is null");
            return (Criteria) this;
        }

        public Criteria andNativeplaceIsNotNull() {
            addCriterion("nativeplace is not null");
            return (Criteria) this;
        }

        public Criteria andNativeplaceEqualTo(String value) {
            addCriterion("nativeplace =", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceNotEqualTo(String value) {
            addCriterion("nativeplace <>", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceGreaterThan(String value) {
            addCriterion("nativeplace >", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceGreaterThanOrEqualTo(String value) {
            addCriterion("nativeplace >=", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceLessThan(String value) {
            addCriterion("nativeplace <", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceLessThanOrEqualTo(String value) {
            addCriterion("nativeplace <=", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceLike(String value) {
            addCriterion("nativeplace like", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceNotLike(String value) {
            addCriterion("nativeplace not like", value, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceIn(List<String> values) {
            addCriterion("nativeplace in", values, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceNotIn(List<String> values) {
            addCriterion("nativeplace not in", values, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceBetween(String value1, String value2) {
            addCriterion("nativeplace between", value1, value2, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andNativeplaceNotBetween(String value1, String value2) {
            addCriterion("nativeplace not between", value1, value2, "nativeplace");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceIsNull() {
            addCriterion("registeredresidence is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceIsNotNull() {
            addCriterion("registeredresidence is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceEqualTo(String value) {
            addCriterion("registeredresidence =", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceNotEqualTo(String value) {
            addCriterion("registeredresidence <>", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceGreaterThan(String value) {
            addCriterion("registeredresidence >", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceGreaterThanOrEqualTo(String value) {
            addCriterion("registeredresidence >=", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceLessThan(String value) {
            addCriterion("registeredresidence <", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceLessThanOrEqualTo(String value) {
            addCriterion("registeredresidence <=", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceLike(String value) {
            addCriterion("registeredresidence like", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceNotLike(String value) {
            addCriterion("registeredresidence not like", value, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceIn(List<String> values) {
            addCriterion("registeredresidence in", values, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceNotIn(List<String> values) {
            addCriterion("registeredresidence not in", values, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceBetween(String value1, String value2) {
            addCriterion("registeredresidence between", value1, value2, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredresidenceNotBetween(String value1, String value2) {
            addCriterion("registeredresidence not between", value1, value2, "registeredresidence");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("nation is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("nation is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("nation =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("nation <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("nation >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("nation >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("nation <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("nation <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("nation like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("nation not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("nation in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("nation not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("nation between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("nation not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationIsNull() {
            addCriterion("politicalaffiliation is null");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationIsNotNull() {
            addCriterion("politicalaffiliation is not null");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationEqualTo(String value) {
            addCriterion("politicalaffiliation =", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationNotEqualTo(String value) {
            addCriterion("politicalaffiliation <>", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationGreaterThan(String value) {
            addCriterion("politicalaffiliation >", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationGreaterThanOrEqualTo(String value) {
            addCriterion("politicalaffiliation >=", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationLessThan(String value) {
            addCriterion("politicalaffiliation <", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationLessThanOrEqualTo(String value) {
            addCriterion("politicalaffiliation <=", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationLike(String value) {
            addCriterion("politicalaffiliation like", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationNotLike(String value) {
            addCriterion("politicalaffiliation not like", value, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationIn(List<String> values) {
            addCriterion("politicalaffiliation in", values, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationNotIn(List<String> values) {
            addCriterion("politicalaffiliation not in", values, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationBetween(String value1, String value2) {
            addCriterion("politicalaffiliation between", value1, value2, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andPoliticalaffiliationNotBetween(String value1, String value2) {
            addCriterion("politicalaffiliation not between", value1, value2, "politicalaffiliation");
            return (Criteria) this;
        }

        public Criteria andEducationlevelIsNull() {
            addCriterion("educationlevel is null");
            return (Criteria) this;
        }

        public Criteria andEducationlevelIsNotNull() {
            addCriterion("educationlevel is not null");
            return (Criteria) this;
        }

        public Criteria andEducationlevelEqualTo(String value) {
            addCriterion("educationlevel =", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelNotEqualTo(String value) {
            addCriterion("educationlevel <>", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelGreaterThan(String value) {
            addCriterion("educationlevel >", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelGreaterThanOrEqualTo(String value) {
            addCriterion("educationlevel >=", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelLessThan(String value) {
            addCriterion("educationlevel <", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelLessThanOrEqualTo(String value) {
            addCriterion("educationlevel <=", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelLike(String value) {
            addCriterion("educationlevel like", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelNotLike(String value) {
            addCriterion("educationlevel not like", value, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelIn(List<String> values) {
            addCriterion("educationlevel in", values, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelNotIn(List<String> values) {
            addCriterion("educationlevel not in", values, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelBetween(String value1, String value2) {
            addCriterion("educationlevel between", value1, value2, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andEducationlevelNotBetween(String value1, String value2) {
            addCriterion("educationlevel not between", value1, value2, "educationlevel");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("company like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("company not like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<String> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<String> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusIsNull() {
            addCriterion("maritalstatus is null");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusIsNotNull() {
            addCriterion("maritalstatus is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusEqualTo(String value) {
            addCriterion("maritalstatus =", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotEqualTo(String value) {
            addCriterion("maritalstatus <>", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusGreaterThan(String value) {
            addCriterion("maritalstatus >", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusGreaterThanOrEqualTo(String value) {
            addCriterion("maritalstatus >=", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusLessThan(String value) {
            addCriterion("maritalstatus <", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusLessThanOrEqualTo(String value) {
            addCriterion("maritalstatus <=", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusLike(String value) {
            addCriterion("maritalstatus like", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotLike(String value) {
            addCriterion("maritalstatus not like", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusIn(List<String> values) {
            addCriterion("maritalstatus in", values, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotIn(List<String> values) {
            addCriterion("maritalstatus not in", values, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusBetween(String value1, String value2) {
            addCriterion("maritalstatus between", value1, value2, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotBetween(String value1, String value2) {
            addCriterion("maritalstatus not between", value1, value2, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andHobbiesIsNull() {
            addCriterion("hobbies is null");
            return (Criteria) this;
        }

        public Criteria andHobbiesIsNotNull() {
            addCriterion("hobbies is not null");
            return (Criteria) this;
        }

        public Criteria andHobbiesEqualTo(String value) {
            addCriterion("hobbies =", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesNotEqualTo(String value) {
            addCriterion("hobbies <>", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesGreaterThan(String value) {
            addCriterion("hobbies >", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesGreaterThanOrEqualTo(String value) {
            addCriterion("hobbies >=", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesLessThan(String value) {
            addCriterion("hobbies <", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesLessThanOrEqualTo(String value) {
            addCriterion("hobbies <=", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesLike(String value) {
            addCriterion("hobbies like", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesNotLike(String value) {
            addCriterion("hobbies not like", value, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesIn(List<String> values) {
            addCriterion("hobbies in", values, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesNotIn(List<String> values) {
            addCriterion("hobbies not in", values, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesBetween(String value1, String value2) {
            addCriterion("hobbies between", value1, value2, "hobbies");
            return (Criteria) this;
        }

        public Criteria andHobbiesNotBetween(String value1, String value2) {
            addCriterion("hobbies not between", value1, value2, "hobbies");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("telephone is null");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("telephone is not null");
            return (Criteria) this;
        }

        public Criteria andTelephoneEqualTo(String value) {
            addCriterion("telephone =", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotEqualTo(String value) {
            addCriterion("telephone <>", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThan(String value) {
            addCriterion("telephone >", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("telephone >=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThan(String value) {
            addCriterion("telephone <", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(String value) {
            addCriterion("telephone <=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLike(String value) {
            addCriterion("telephone like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotLike(String value) {
            addCriterion("telephone not like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneIn(List<String> values) {
            addCriterion("telephone in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotIn(List<String> values) {
            addCriterion("telephone not in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneBetween(String value1, String value2) {
            addCriterion("telephone between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotBetween(String value1, String value2) {
            addCriterion("telephone not between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andMailIsNull() {
            addCriterion("mail is null");
            return (Criteria) this;
        }

        public Criteria andMailIsNotNull() {
            addCriterion("mail is not null");
            return (Criteria) this;
        }

        public Criteria andMailEqualTo(String value) {
            addCriterion("mail =", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotEqualTo(String value) {
            addCriterion("mail <>", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailGreaterThan(String value) {
            addCriterion("mail >", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailGreaterThanOrEqualTo(String value) {
            addCriterion("mail >=", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLessThan(String value) {
            addCriterion("mail <", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLessThanOrEqualTo(String value) {
            addCriterion("mail <=", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLike(String value) {
            addCriterion("mail like", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotLike(String value) {
            addCriterion("mail not like", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailIn(List<String> values) {
            addCriterion("mail in", values, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotIn(List<String> values) {
            addCriterion("mail not in", values, "mail");
            return (Criteria) this;
        }

        public Criteria andMailBetween(String value1, String value2) {
            addCriterion("mail between", value1, value2, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotBetween(String value1, String value2) {
            addCriterion("mail not between", value1, value2, "mail");
            return (Criteria) this;
        }

        public Criteria andImmigratedateIsNull() {
            addCriterion("immigratedate is null");
            return (Criteria) this;
        }

        public Criteria andImmigratedateIsNotNull() {
            addCriterion("immigratedate is not null");
            return (Criteria) this;
        }

        public Criteria andImmigratedateEqualTo(Date value) {
            addCriterionForJDBCDate("immigratedate =", value, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("immigratedate <>", value, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateGreaterThan(Date value) {
            addCriterionForJDBCDate("immigratedate >", value, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("immigratedate >=", value, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateLessThan(Date value) {
            addCriterionForJDBCDate("immigratedate <", value, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("immigratedate <=", value, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateIn(List<Date> values) {
            addCriterionForJDBCDate("immigratedate in", values, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("immigratedate not in", values, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("immigratedate between", value1, value2, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andImmigratedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("immigratedate not between", value1, value2, "immigratedate");
            return (Criteria) this;
        }

        public Criteria andQuitdateIsNull() {
            addCriterion("quitdate is null");
            return (Criteria) this;
        }

        public Criteria andQuitdateIsNotNull() {
            addCriterion("quitdate is not null");
            return (Criteria) this;
        }

        public Criteria andQuitdateEqualTo(Date value) {
            addCriterionForJDBCDate("quitdate =", value, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("quitdate <>", value, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateGreaterThan(Date value) {
            addCriterionForJDBCDate("quitdate >", value, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("quitdate >=", value, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateLessThan(Date value) {
            addCriterionForJDBCDate("quitdate <", value, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("quitdate <=", value, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateIn(List<Date> values) {
            addCriterionForJDBCDate("quitdate in", values, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("quitdate not in", values, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("quitdate between", value1, value2, "quitdate");
            return (Criteria) this;
        }

        public Criteria andQuitdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("quitdate not between", value1, value2, "quitdate");
            return (Criteria) this;
        }

        public Criteria andPropertyownerIsNull() {
            addCriterion("propertyowner is null");
            return (Criteria) this;
        }

        public Criteria andPropertyownerIsNotNull() {
            addCriterion("propertyowner is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyownerEqualTo(String value) {
            addCriterion("propertyowner =", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerNotEqualTo(String value) {
            addCriterion("propertyowner <>", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerGreaterThan(String value) {
            addCriterion("propertyowner >", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerGreaterThanOrEqualTo(String value) {
            addCriterion("propertyowner >=", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerLessThan(String value) {
            addCriterion("propertyowner <", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerLessThanOrEqualTo(String value) {
            addCriterion("propertyowner <=", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerLike(String value) {
            addCriterion("propertyowner like", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerNotLike(String value) {
            addCriterion("propertyowner not like", value, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerIn(List<String> values) {
            addCriterion("propertyowner in", values, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerNotIn(List<String> values) {
            addCriterion("propertyowner not in", values, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerBetween(String value1, String value2) {
            addCriterion("propertyowner between", value1, value2, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyownerNotBetween(String value1, String value2) {
            addCriterion("propertyowner not between", value1, value2, "propertyowner");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityIsNull() {
            addCriterion("propertyowneridentity is null");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityIsNotNull() {
            addCriterion("propertyowneridentity is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityEqualTo(String value) {
            addCriterion("propertyowneridentity =", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityNotEqualTo(String value) {
            addCriterion("propertyowneridentity <>", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityGreaterThan(String value) {
            addCriterion("propertyowneridentity >", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityGreaterThanOrEqualTo(String value) {
            addCriterion("propertyowneridentity >=", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityLessThan(String value) {
            addCriterion("propertyowneridentity <", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityLessThanOrEqualTo(String value) {
            addCriterion("propertyowneridentity <=", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityLike(String value) {
            addCriterion("propertyowneridentity like", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityNotLike(String value) {
            addCriterion("propertyowneridentity not like", value, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityIn(List<String> values) {
            addCriterion("propertyowneridentity in", values, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityNotIn(List<String> values) {
            addCriterion("propertyowneridentity not in", values, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityBetween(String value1, String value2) {
            addCriterion("propertyowneridentity between", value1, value2, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andPropertyowneridentityNotBetween(String value1, String value2) {
            addCriterion("propertyowneridentity not between", value1, value2, "propertyowneridentity");
            return (Criteria) this;
        }

        public Criteria andUserpassidIsNull() {
            addCriterion("userpassid is null");
            return (Criteria) this;
        }

        public Criteria andUserpassidIsNotNull() {
            addCriterion("userpassid is not null");
            return (Criteria) this;
        }

        public Criteria andUserpassidEqualTo(Integer value) {
            addCriterion("userpassid =", value, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidNotEqualTo(Integer value) {
            addCriterion("userpassid <>", value, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidGreaterThan(Integer value) {
            addCriterion("userpassid >", value, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidGreaterThanOrEqualTo(Integer value) {
            addCriterion("userpassid >=", value, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidLessThan(Integer value) {
            addCriterion("userpassid <", value, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidLessThanOrEqualTo(Integer value) {
            addCriterion("userpassid <=", value, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidIn(List<Integer> values) {
            addCriterion("userpassid in", values, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidNotIn(List<Integer> values) {
            addCriterion("userpassid not in", values, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidBetween(Integer value1, Integer value2) {
            addCriterion("userpassid between", value1, value2, "userpassid");
            return (Criteria) this;
        }

        public Criteria andUserpassidNotBetween(Integer value1, Integer value2) {
            addCriterion("userpassid not between", value1, value2, "userpassid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table roomowner
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 22 10:59:42 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table roomowner
     *
     * @mbggenerated Thu Jan 22 10:59:42 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}