package com.smartcommunity.pojo;

public class Userrolejoin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrolejoin.id
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrolejoin.userpassid
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    private Integer userpassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrolejoin.roleid
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrolejoin.id
     *
     * @return the value of userrolejoin.id
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrolejoin.id
     *
     * @param id the value for userrolejoin.id
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrolejoin.userpassid
     *
     * @return the value of userrolejoin.userpassid
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public Integer getUserpassid() {
        return userpassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrolejoin.userpassid
     *
     * @param userpassid the value for userrolejoin.userpassid
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public void setUserpassid(Integer userpassid) {
        this.userpassid = userpassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrolejoin.roleid
     *
     * @return the value of userrolejoin.roleid
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrolejoin.roleid
     *
     * @param roleid the value for userrolejoin.roleid
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}