package com.smartcommunity.pojo;

public class Userpass {
	/** add */
	java.util.Set<Userrolejoin> roles;
    public java.util.Set<Userrolejoin> getRoles() {
		return roles;
	}

	public void setRoles(java.util.Set<Userrolejoin> roles) {
		this.roles = roles;
	}
	/** addend */
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpass.id
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpass.name
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpass.password
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpass.salt
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpass.id
     *
     * @return the value of userpass.id
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpass.id
     *
     * @param id the value for userpass.id
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpass.name
     *
     * @return the value of userpass.name
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpass.name
     *
     * @param name the value for userpass.name
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpass.password
     *
     * @return the value of userpass.password
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpass.password
     *
     * @param password the value for userpass.password
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpass.salt
     *
     * @return the value of userpass.salt
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpass.salt
     *
     * @param salt the value for userpass.salt
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }
}