package com.smartcommunity.pojo;

public class Userrepair {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrepair.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrepair.userid
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrepair.devicename
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private String devicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrepair.description
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrepair.count
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrepair.id
     *
     * @return the value of userrepair.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrepair.id
     *
     * @param id the value for userrepair.id
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrepair.userid
     *
     * @return the value of userrepair.userid
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrepair.userid
     *
     * @param userid the value for userrepair.userid
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrepair.devicename
     *
     * @return the value of userrepair.devicename
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public String getDevicename() {
        return devicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrepair.devicename
     *
     * @param devicename the value for userrepair.devicename
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setDevicename(String devicename) {
        this.devicename = devicename == null ? null : devicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrepair.description
     *
     * @return the value of userrepair.description
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrepair.description
     *
     * @param description the value for userrepair.description
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrepair.count
     *
     * @return the value of userrepair.count
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrepair.count
     *
     * @param count the value for userrepair.count
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}