package com.smartcommunity.mapper;

import com.smartcommunity.pojo.AccountRecord;
import com.smartcommunity.pojo.AccountRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int countByExample(AccountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int deleteByExample(AccountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int insert(AccountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int insertSelective(AccountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    List<AccountRecord> selectByExample(AccountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    AccountRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") AccountRecord record, @Param("example") AccountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int updateByExample(@Param("record") AccountRecord record, @Param("example") AccountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int updateByPrimaryKeySelective(AccountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbggenerated Sat Jan 24 19:27:37 CST 2015
     */
    int updateByPrimaryKey(AccountRecord record);
}