package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Complaintsimages;
import com.smartcommunity.pojo.ComplaintsimagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplaintsimagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int countByExample(ComplaintsimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int deleteByExample(ComplaintsimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int insert(Complaintsimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int insertSelective(Complaintsimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    List<Complaintsimages> selectByExample(ComplaintsimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    Complaintsimages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") Complaintsimages record, @Param("example") ComplaintsimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int updateByExample(@Param("record") Complaintsimages record, @Param("example") ComplaintsimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int updateByPrimaryKeySelective(Complaintsimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaintsimages
     *
     * @mbggenerated Wed Jan 14 09:34:17 CST 2015
     */
    int updateByPrimaryKey(Complaintsimages record);
}