package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Devicefault;
import com.smartcommunity.pojo.DevicefaultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevicefaultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int countByExample(DevicefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int deleteByExample(DevicefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int insert(Devicefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int insertSelective(Devicefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    List<Devicefault> selectByExample(DevicefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    Devicefault selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") Devicefault record, @Param("example") DevicefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByExample(@Param("record") Devicefault record, @Param("example") DevicefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByPrimaryKeySelective(Devicefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicefault
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByPrimaryKey(Devicefault record);
}