package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Meter;
import com.smartcommunity.pojo.MeterExample;

import edu.hust.smartcommunity.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int countByExample(MeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int deleteByExample(MeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int insert(Meter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int insertSelective(Meter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    List<Meter> selectByExample(MeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    Meter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") Meter record, @Param("example") MeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int updateByExample(@Param("record") Meter record, @Param("example") MeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int updateByPrimaryKeySelective(Meter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meter
     *
     * @mbggenerated Sat Jan 24 16:00:04 CST 2015
     */
    int updateByPrimaryKey(Meter record);
    /**
     * add_y
     */
    PageList<Meter> selectByExample(MeterExample example,edu.hust.smartcommunity.paginator.domain.PageBounds pageBounds);;

}