package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Userpass;
import com.smartcommunity.pojo.UserpassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserpassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int countByExample(UserpassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int deleteByExample(UserpassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int insert(Userpass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int insertSelective(Userpass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    List<Userpass> selectByExample(UserpassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    Userpass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") Userpass record, @Param("example") UserpassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByExample(@Param("record") Userpass record, @Param("example") UserpassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByPrimaryKeySelective(Userpass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpass
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByPrimaryKey(Userpass record);
    /** add */
    List<Userpass> selectUserpassAndRolesByExample(@Param("example") UserpassExample userpassExample);
}