package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Userrepair;
import com.smartcommunity.pojo.UserrepairExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserrepairMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int countByExample(UserrepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int deleteByExample(UserrepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int insert(Userrepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int insertSelective(Userrepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    List<Userrepair> selectByExample(UserrepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    Userrepair selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") Userrepair record, @Param("example") UserrepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByExample(@Param("record") Userrepair record, @Param("example") UserrepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByPrimaryKeySelective(Userrepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrepair
     *
     * @mbggenerated Tue Jan 06 14:55:46 CST 2015
     */
    int updateByPrimaryKey(Userrepair record);
}