package com.smartcommunity.mapper;

import com.smartcommunity.pojo.UserNotice;
import com.smartcommunity.pojo.UserNoticeExample;

import edu.hust.smartcommunity.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int countByExample(UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int deleteByExample(UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int insert(UserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int insertSelective(UserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    List<UserNotice> selectByExample(UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    UserNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserNotice record, @Param("example") UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int updateByExample(@Param("record") UserNotice record, @Param("example") UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int updateByPrimaryKeySelective(UserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Sun Jan 25 19:11:11 CST 2015
     */
    int updateByPrimaryKey(UserNotice record);
    /** add_y */
    int insertMulti(List<UserNotice> records);

    PageList<UserNotice> selectByExample(UserNoticeExample example,edu.hust.smartcommunity.paginator.domain.PageBounds pageBounds);
}