package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Userrolejoin;
import com.smartcommunity.pojo.UserrolejoinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserrolejoinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int countByExample(UserrolejoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int deleteByExample(UserrolejoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int insert(Userrolejoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int insertSelective(Userrolejoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    List<Userrolejoin> selectByExample(UserrolejoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    Userrolejoin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") Userrolejoin record, @Param("example") UserrolejoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByExample(@Param("record") Userrolejoin record, @Param("example") UserrolejoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByPrimaryKeySelective(Userrolejoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolejoin
     *
     * @mbggenerated Tue Jan 20 16:35:08 CST 2015
     */
    int updateByPrimaryKey(Userrolejoin record);
    // add_y

    int insertMulti(List<Userrolejoin> records);
}